//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA41Team02B
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.Trans = new HashSet<Tran>();
        }
    
        public string MemberID { get; set; }
        public string MemberName { get; set; }
        public string NRIC { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Gender { get; set; }
        public long ContactNumber { get; set; }
        public string Status { get; set; }
        public string Address { get; set; }
        public string EmailAddress { get; set; }
        public string Remarks { get; set; }
    
        public virtual ICollection<Tran> Trans { get; set; }
    }
}
